# Generated by Django 4.1.3 on 2023-01-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cantidad_habitaciones', models.IntegerField()),
                ('cantidad_personas', models.IntegerField()),
                ('mascotas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='viajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('destino', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('adulto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('salida', models.DateField()),
                ('llegada', models.DateField()),
                ('cantidad_pasajes', models.IntegerField()),
                ('empresa', models.CharField(max_length=100)),
            ],
        ),
    ]
