# Generated by Django 4.1.3 on 2023-01-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTraveling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
